name: PR Validation

on: [push, pull_request, workflow_dispatch]

env:
  ACTIONS_RUNNER_DEBUG: 'true'
  ACTIONS_STEP_DEBUG: 'true'

jobs:
  build:
    name: TF Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.14.0"

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform test
        id: test
        run: terraform test -no-color

